defaults:
  - _self_
  - candidate-generation: random.yaml
  - geo-estimation: random.yaml
  - location-ranking: random.yaml
  - metadata-extractor: empty.yaml 
  - streetview-image-scraper: random.yaml
img: assets/paris.jpeg